package main

import "fmt"

func main() {
	days := [...]string{"Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"}

	fmt.Println(days)

	sliceDays := days[4:]
	// BUKAN MENGGANTI NILAI SLICENYA MELAINKAN MENGGANTI REFERENSI DARI ARRAY "days"
	sliceDays[0] = "Jumat1"
	sliceDays[1] = "Sabtu1"
	// sliceDays[4] = "Jumat Baru" // PERHATIKAN NILAI INDEXNYA APABILA MELEBIHI DARI POINTER AKHIRNYA MAKA AKAN ERROR
	// APABILA DI PRINT MAKA ARRAY AKAN BERUBAH NILAINYA
	fmt.Println(days)

	// PERLU DIPERHATIKAN KAPASITAS SANGAT BERPENGARUH DALAM HAL INI
	// APABILA PENAMBAHAN DATA BELUM MENCAPAI ATAU BELUM MELEBIHI MAKSIMAL KAPASITAS
	// MAKA TIDAK AKAN DIBUATKAN ARRAY BARU, KETIKA SUDAH MELEBIHI KAPASITAS MAKA AKAN DIBUATKAN ARRAY BARU
	sliceDays2 := append(sliceDays, "Senin1") // DISINI MENAMBAHKAN DATA
	sliceDays2[0] = "SeninUpdated"            // DIUPDATE DI SLICE TERSEBUT DI INDEX KE 0, DISINI AKAN ADA PENGECEKAN APA DIBUATKAN ARRAY BARU ATAU TIDAK
	// JIKA BELUM MELEBIHI BATAS MAKSIMAL KAPASITAS MAKA AKAN MENGAKSES ARRAY REFERENSINYA
	// JIKA SUDAH MELEBIHI BATAS MAKSIMAL KAPASITAS MAKA AKAN DIBUATKAN ARRAY BARU SEHINGGA
	// KETIKA ADA PERUBAHAN DI "sliceDays2" TIDAK AKAN MEMPENGARUHI REFERENSI ARRAY "days"
	fmt.Println(sliceDays2)
	fmt.Println(days)
}
